name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ggranzotto 
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ggranzotto/app_tests:latest

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: "82.112.245.176"
        username: "root"
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ggranzotto/app_tests:latest
          docker stop meu_container || true
          docker rm meu_container || true
          docker run -d -p 8000:8000 --name meu_container \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            ggranzotto/app_tests:latest
